config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users, except: [:new] do
    resources :compositions do
      resources :comments
    end
  end

  resources :sessions, only: [:create]

  get '/map' => 'pages#index'
  get '/votes' => 'pages#votes'
  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :composition

end

app/models/composition.rb
class Composition < ActiveRecord::Base

  belongs_to :user
  has_many :comments
  has_many :users, :through => :comments

  validates :title, presence: true
  validates :user, presence: true
  validates :latitude,
    presence: true,
    numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }
    # question: why do the below two formats throw errors?
    #format: { with: /^(-?[1-8]?\d(?:\.\d{1,6})?|90(?:\.0{1,6})?)$/ }
  validates :longitude,
    presence: true,
    numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
    #format: { with: /^(-?(?:1[0-7]|[1-9])?\d(?:\.\d{1,6})?|180(?:\.0{1,6})?)$/ }

    acts_as_gmappable :process_geocoding => false

end

app/models/user.rb
class User < ActiveRecord::Base

  # user can have many compositions that should be destroyed with user
  has_many :compositions, dependent: :destroy
  has_many :comments
  has_many :comments, :through => :compositions

  # add handlers to run when creating and saving:
  before_create :create_remember_token
  before_save :normalize_fields

  # validate name:
  validates :name,
    presence: true,
    length: {  maximum:50 }

  # validate email address:
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  # secure password features:
  has_secure_password

  # question: why are the below two methods not implied by has_secure_password?

  # create a new remember token for a user:
  # question: why are these not in the controller?
  # question: what is all this doing under the hood?
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # hash a remember token:
  # question: does the hash methods come from has_secure_password?
  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  # create a new session token for the user:
  # question: does the remember_token method come from has_secure_password?
  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end

  # normalize fields for consistency:
  def normalize_fields
    self.email.downcase!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @composition = Composition.find(params[:composition_id])
    @comment = Comment.new
    @comment.entry = params[:comment][:entry]
    @comment.composition = @composition
    @comment.user = current_user
    @comment.save
    redirect_to user_composition_path(current_user, @composition)
  end

end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController
  before_action :find_user
  before_action :find_composition, only: [:show, :edit, :update]
  before_action :load_composition, only: [:destroy]

  def index
    @compositions = @user.compositions.all
    @json = @compositions.to_gmaps4rails do |composition, marker|
      marker.infowindow render_to_string(:partial => "/compositions/infowindow", :locals => {composition: composition})
    end
  end

  def new
    @composition = Composition.new
  end

  def create
    @composition = @user.compositions.build(composition_params)
      if @composition.save
        redirect_to user_compositions_path(@user)
      else
        flash[:error] = "please complete the form"
        render :new
      end
  end

  def show
    @json = @composition.to_gmaps4rails
    @comment = Comment.new
    @comments = Comment.where(composition_id: @composition.id).order('updated_at DESC').limit(5)
  end

  def edit
  end

  def update
    if @composition.update(composition_params)
      redirect_to user_composition_path
    else
      render :edit
    end
  end

  def destroy
    @composition.destroy
    redirect_to user_compositions_path
  end

private

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_composition
    @composition = Composition.find(params[:id])
  end

  def composition_params
    params.require(:composition).permit(
      :title,
      :latitude,
      :longitude,
      :image_url,
      :description,
      :user_id
    )
  end

  def load_composition
    return @composition = Composition.find_by(id: params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @compositions = Composition.all
    @json = @compositions.to_gmaps4rails do |composition, marker|
      marker.infowindow render_to_string(:partial => "/compositions/infowindow", :locals => {composition: composition})
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if signed_in?
      redirect_to user_path(current_user)
    end
  end

  def create
    # Find the user by email:
    user = User.find_by(email: params[:session][:email].downcase)

    # Test if the user was found AND authenticates
    if user && user.authenticate(params[:session][:password])
      sign_in user
    # question, should I have changed the below to user?
      redirect_back_or user
    else
      flash[:error] = 'Invalid email/password'
      redirect_to signin_path
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, except: [:new, :create]

  # index user artwork
  def index
    @compositions = Composition.all
  end

  # feed the user new view a blank user
  def new
    @user = User.new
  end

  # allow the user to submit strong params
  # if the save is successful, redirect to user new view
  # else render user new view to start the process over
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

private

  # grabs user id from params to find the correct user
  def find_user
    @user = User.find(params[:id])
  end

  # set strong params for creating a user
  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :profile_picture
    )
  end

  def require_current_user
    if !current_user?(@user)
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # current user methods:

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

# question: how do these two current_user methods interact?

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    current_user == user
  end

  # signin status methods:

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  # location management methods:

  def store_location
    if request.get?
      session[:return_to] = request.url
    end
  end

# question: I do not understand the below
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  # security checkpoint method:

  def require_signin
    unless signed_in?
      store_location
      flash[:error] = 'Please sign in.'
      redirect_to signin_url
    end
  end

end

app/views/common/_signout.html.erb
<nav class="navigation">
  <ul>
  <% if signed_in? %>

    <%= form_for :session, url: signout_path, method: 'delete' do |f| %>
      <li>Signed in as <%= link_to current_user.name, current_user %>
    <%= f.submit "Sign out", id: 'signout' %></li>

    <% if current_user %>
      <div class="navigation">
        <ul>
          <li><%= link_to "edit profile", edit_user_path(current_user) %></li>
          <li><%= link_to "compositions", user_compositions_path(current_user) %></li>
          <li><%= link_to "map", map_path %></li>
          <li><%= link_to "upload piece", new_user_composition_path(current_user) %></li>
        </ul>
      </div>
    <% end %>

  <% end %>

  <% else %>

    <%= link_to "Sign up", signup_path, class: "signup_button" %>

  <% end %>
</ul>
</nav>

app/views/compositions/_composition_form.html.erb
<div class="uploadform_container">
  <div class="upload_form">
    <%= form_for [@user, @composition] do |f| %>
      <%= f.text_field :title, placeholder: 'title', class: 'uploadform_field' %>
      <%= f.hidden_field :user_id, value: @user.id %>
      <%= f.number_field :latitude, step: 'any', placeholder: 'latitude', class: 'uploadform_field'    %>
      <%= f.number_field :longitude, step: 'any', placeholder: 'longitude', class: 'uploadform_field' %>
      <%= f.text_field :image_url, placeholder: 'image url', class: 'uploadform_field' %>
      <!--chand area to field-->
      <!--%= f.text_field :description, placeholder: 'description', size: '20x10' %-->
      <%= f.submit 'Submit', id: 'submit' %>
    <% end %>
    <%= link_to "cancel", user_path(@user) %>
   </div>
</div>

app/views/compositions/_infowindow.html.erb
<a href="/users/3/compositions/<%= composition.id %>"><h4><%= composition.title %></h4></a>
<img src="<%= composition.image_url %>"
style='max-height:90px; max-width:90px;'>
<p><%= composition.latitude %> N,
  <%= composition.longitude %> W</p>

app/views/compositions/edit.html.erb
<h1>edit your piece:</h1>

<% flash.each do |name, msg| %>
  <%= content_tag :p, msg, class: name %>

<% end %>
<%= render 'composition_form' %>

app/views/compositions/index.html.erb
<div class="compositionindex_container">

  <div class="gmap">
    <%= gmaps4rails(@json) %>
  </div>

  <div class="static_profile">
    <h1><%= @user.name %>'s gallery:</h1>
    <img src="<%= @user.profile_picture %>" class="profile_picture">
  </div>




<p><%= link_to "home", user_path(@user) %></p>


</div>

app/views/compositions/new.html.erb
<h1>add to your collection:</h1>

<!--how does the below work?-->
<% flash.each do |name, msg| %>
  <%= content_tag :p, msg, class: name %>

<% end %>
<%= render 'composition_form' %>

app/views/compositions/show.html.erb
<div class="compositionshow_container">

  <div class="gmap">
    <%= gmaps4rails(@json) %>
  </div>

  <div class="static_profile">
    <h1><%= @composition.title %></h1>
    <img src="<%= @composition.image_url %>" class="compositionshow_image">
  </div>

  <% if @user == @composition.user %>
    <%= form_for [@user, @composition], method: 'delete' do |f| %>
      <%= f.submit "remove composition", id: "destroy" %>
    <% end %>
  <% end %>

  <div class="comments ">
    <p><u>comments:</u></p>
    <div class="composition-comments">
      <% @comments.each do |comment| %>
      <div class="comment_block">
        <p><%= comment.entry %></p>
        <p> * <%= comment.user.email %> * <%= time_ago_in_words(comment.updated_at) %> ago</p>
        <br>
      </div>
      <% end %>


      <% if current_user %>
        <%= form_for [@user, @composition, @comment] do |f| %>
          <%= f.text_area :entry, size: "40x10" %>
          <%= f.submit "comment" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paintmycity</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= yield(:css_includes) if content_for?(:css_includes) %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= javascript_include_tag 'application' %>
  <div class="page">

<!--%= link_to "Home", root_path %-->
<%= render 'common/signout' %>
<%= yield %>
<%= yield :scripts %>

  </div>
</body>
</html>

app/views/pages/index.html.erb
<div class="pages_container">
  <div class="gmap">
      <%= gmaps4rails(@json) %>
  </div>

  <div class="static_profile">
      <h1>get out there <%= current_user.name %>:</h1>
      <img src="<%= current_user.profile_picture %>" class="profile_picture">
  </div>
</div>

app/views/users/_user_form.html.erb
<div class="user_form_container">
  <% if @user.errors.any? %>
    <b>Errors:</b>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="user_form">
    <%= form_for @user do |f| %>
      <%= f.text_field :name, placeholder: "name", class: "userform_field" %>
      <%= f.text_field :email, placeholder: "email", class: "userform_field" %>
      <%= f.password_field :password, placeholder: "password", class: "userform_field" %>
      <%= f.password_field :password_confirmation, placeholder: "confirm password", class: "userform_field" %>
      <%= f.text_field :profile_picture, placeholder: "profile picture", class: "userform_field" %>
      <%= f.submit "submit", id: 'submit', class: "submit_button" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>edit <%= @user.name %></h1>
<%= render "user_form" %>

<hr>

<%= link_to "Cancel", @user %>

app/views/users/index.html.erb
<h1>map</h1>

app/views/users/new.html.erb
<h1>create account</h1>
<%= render "user_form" %>
<%= link_to "Cancel", root_path %>

app/views/users/show.html.erb
<div class="usershow_container">

  <div class="profile">
    <p><%= @user.profile %></p>
  </div>

  <div class="static_profile">
    <h1><%= @user.name %></h1>
    <img src="<%= @user.profile_picture %>" class="profile_picture">
  </div>
</div>